### ISSUE TITLE
Electrum even 3.3.8 lost all rvn?

### ISSUE THREAD

**Issue by patricmcgovern98** [standard-error/electrum-raven#15]
I had my rvn stored on my electrum 3.3.8 wallet and then I checked in this morning and saw it was not connected had my balance but said wasn’t connected after another two hours of waiting it was yellow and said server is lagging (500270) blocks . Saved my seed Deleted the wallet and rvn.dam file and installed again and I loaded as a new wallet with me pre-existing seed and now it has no balance and won’t connect. I went on my other computer and it won’t connect either. Did vpn’s and different servers. So lost plz help

**Comment by standard-error** [comment]
RVN hard forked on May 7 and the changes are incompatible with Electrum-RVN 3.3.8-2. An update is being worked on but is not available yet. 

See https://github.com/standard-error/electrum-raven/issues/13 for options if you need immediate access to your wallet. Otherwise there is no need to do anything except wait for the update.
